# Generated by Django 5.2.13 on 2026-05-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_price_player_credit_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
