# Generated by Django 5.2.13 on 2026-05-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasy_team',
            name='remaining_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='player_match_performance',
            name='maidens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='budget_cap',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
