# Generated by Django 5.2.13 on 2026-07-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_transaction_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='invite_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
