# Generated by Django 5.2.13 on 2026-07-23 10:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_league_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='cricbuzz_match_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='cricbuzz_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('innings_number', models.IntegerField()),
                ('total_runs', models.IntegerField(default=0)),
                ('total_wickets', models.IntegerField(default=0)),
                ('overs', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('extras', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cricket_team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='core.match')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('source_name', models.CharField(max_length=100)),
                ('source_url', models.URLField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='core.tournament')),
            ],
        ),
    ]
