# Generated by Django 5.2.13 on 2026-07-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_match_cricbuzz_match_id_player_cricbuzz_id_innings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='batting_style',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='bowling_style',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
