# Generated by Django 5.2.13 on 2026-07-26 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_player_batting_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_match_performance',
            name='innings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='core.innings'),
        ),
    ]
