# Generated by Copilot to store bowling overs on player match performances.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_player_match_performance_innings'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_match_performance',
            name='overs_bowled',
            field=models.DecimalField(
                decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
