# Generated by Django 5.2.13 on 2026-07-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_player_match_performance_overs_bowled'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_match_performance',
            name='how_out',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
