# Generated by Django 5.2.13 on 2026-07-30 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_player_match_performance_how_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_players',
            field=models.ManyToManyField(blank=True, related_name='fans', to='core.player'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fans', to='core.cricket_team'),
        ),
    ]
