# Generated by Django 5.2.13 on 2026-07-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_favorite_players_user_favorite_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
